-- ============================================================================
-- OBSOLETO — no usar. Reemplazado por:
--     supabase/optional/cron_check_freshness.sql
-- ============================================================================
-- Este archivo contenía la URL del proyecto antiguo (xpubdazwixxdckiunhvt) y
-- una clave JWT escrita en texto plano, versionada en GitHub. Se vació el
-- 2026-09-13 durante la migración.
--
-- El reemplazo lee la URL y el token de la configuración de la base
-- (current_setting), en vez de incrustarlos:
--
--   alter database postgres set app.settings.project_url = 'https://<ref>.supabase.co';
--   alter database postgres set app.settings.freshness_token = '<token>';
--
-- La clave que estaba aquí pertenece al proyecto viejo y sigue viva en el
-- historial de git. Conviene rotarla en ese proyecto.
-- ============================================================================
