-- Durable edge outbox idempotency.
-- The N100 assigns one UUID to every event before persisting it locally.  This
-- column lets retries use ON CONFLICT without duplicating already accepted rows.

alter table public.events
  add column if not exists source_event_id uuid;

comment on column public.events.source_event_id is
  'Idempotency UUID generated by the edge durable outbox';

create unique index if not exists events_source_event_id_uidx
  on public.events (source_event_id);

notify pgrst, 'reload schema';
