-- ============================================================================
-- BASELINE · Modelo central de Lens
-- ============================================================================
-- Cierra C-15 (AUDITORIA_LENS.md): hasta ahora el modelo central solo existía
-- en la base viva del proyecto xpubdazwixxdckiunhvt, fuera de la organización
-- PixelCivik. Este archivo lo pone bajo control de versiones.
--
-- Prefijo 20260101 deliberado: es anterior a las 15 migraciones existentes
-- (la primera es 20260819), para que sigan aplicándose después y en orden.
--
-- PROCEDENCIA DE CADA DATO
--
--   [PROBADO]  Verificado contra la base viva el 2026-09-12 por introspección
--              vía PostgREST con la anon key:
--                · nombres y orden de columnas  -> select=* (orden ordinal)
--                · tipo exacto                  -> error de casteo de Postgres
--                · existencia de FK             -> el embedding de PostgREST
--                                                  solo funciona con constraint real
--                · nulabilidad EXACTA           -> introspección de pg_graphql:
--                                                  un campo NON_NULL en GraphQL es
--                                                  exactamente una columna NOT NULL.
--                                                  Oráculo fiable incluso con DEFAULT:
--                                                  verificado contra shoplifting_alerts,
--                                                  cuyas columnas 'not null default ...'
--                                                  del repo salen todas NON_NULL.
--                · UNIQUE/PK en destinos de FK  -> Postgres lo exige para la FK
--
--   [INFERIDO] No observable con la anon key. Requiere el dump real para
--              confirmarse. Cada caso está anotado en su línea.
--
-- LO QUE ESTE ARCHIVO NO CONTIENE (no es observable sin acceso de Owner):
--   índices no-PK, CHECK constraints, triggers, defaults de servidor salvo los
--   anotados, policies RLS y grants reales, extensiones y jobs de cron.
--   Ver MIGRACION_A_PIXEL.md, paso 4: `supabase db diff` los revela de una vez.
--
-- SEGURIDAD: este baseline habilita RLS sin ninguna policy, es decir cerrado.
--   NO reproduce los grants a `anon` que hoy tiene producción; esa cadena es el
--   hallazgo P1 C-04. Para paridad con producción, aplicar explícitamente
--   optional/anon_read_paridad_produccion.sql.
-- ============================================================================

-- ─── event_groups ──────────────────────────────────────────────────────────
-- [PROBADO] existe; es destino de FK desde event_types.group_id.
-- [PROBADO] tiene las columnas id, code, label, description.
-- NOTA: con la anon key devuelve 0 filas, pero event_types.group_id = 1 con FK
--   real exige que la fila id=1 exista. Está oculta por RLS o por falta de
--   grant. Sus valores no se pudieron leer: ver seed.sql.
create table if not exists public.event_groups (
  id          bigint generated by default as identity primary key,  -- [INFERIDO] identity
  code        text not null,                                        -- [INFERIDO] not null
  label       text,
  description text
);

-- ─── sites ─────────────────────────────────────────────────────────────────
create table if not exists public.sites (
  id         bigint      generated by default as identity primary key, -- [PROBADO] bigint + PK (destino de FK) · [INFERIDO] identity
  name       text        not null,                                     -- [INFERIDO] not null (0 nulls en 2 filas)
  slug       text        not null,                                     -- [INFERIDO] not null + [INFERIDO] unique
  created_at timestamptz default now()                                 -- [PROBADO] timestamptz y NULLABLE · [INFERIDO] default
);

-- ─── cameras ───────────────────────────────────────────────────────────────
create table if not exists public.cameras (
  id      bigint  generated by default as identity primary key,  -- [PROBADO] bigint + PK · [INFERIDO] identity
  site_id bigint  not null references public.sites(id),          -- [PROBADO] FK a sites
  channel text    not null,                                      -- [INFERIDO] not null
  active  boolean default true,                                  -- [PROBADO] boolean y NULLABLE (GraphQL 'active Boolean') · [INFERIDO] default
  name    text                                                   -- [PROBADO] NULLABLE (6/6 filas NULL)
);

-- ─── event_types ───────────────────────────────────────────────────────────
create table if not exists public.event_types (
  id              bigint  generated by default as identity primary key, -- [PROBADO] bigint + PK
  group_id        bigint  references public.event_groups(id),           -- [PROBADO] FK a event_groups
  code            text    not null,                                     -- [INFERIDO] not null + unique
  label           text,
  has_duration    boolean default false,                                -- [PROBADO] boolean y NULLABLE
  is_entry        boolean default false,                                -- [PROBADO] boolean y NULLABLE
  has_person_attr boolean default false                                 -- [PROBADO] boolean y NULLABLE
);

-- ─── person_classes ────────────────────────────────────────────────────────
-- Catálogo de clases género × grupo de edad. [PROBADO] sin FK a event_types.
create table if not exists public.person_classes (
  id              bigint      generated by default as identity primary key,
  code            text        not null,                     -- [INFERIDO] not null + unique
  gender_code     text        not null,                     -- [PROBADO] NOT NULL (GraphQL 'gender_code String!')
  age_group_code  text        not null,                     -- [PROBADO] NOT NULL
  gender_label    text,
  age_group_label text,
  label           text,
  created_at      timestamptz default now()                 -- [PROBADO] timestamptz y NULLABLE
);

-- ─── events ────────────────────────────────────────────────────────────────
-- Tabla de hechos. NO incluye source_event_id a propósito: esa columna la
-- agrega 20260902183500_events_source_event_id.sql, que se aplica después.
--
-- `time` es timestamptz. [PROBADO] contra la base viva. Es el punto exacto que
-- la auditoría marcaba como corrupción silenciosa si se adivinaba `timestamp`.
create table if not exists public.events (
  id            bigint      generated by default as identity primary key, -- [INFERIDO] identity
  site_id       bigint      not null references public.sites(id),         -- [PROBADO] FK
  camera_id     bigint      references public.cameras(id),                -- [PROBADO] FK y NULLABLE. Declararlo NOT NULL rechazaria eventos sin camara al reimportar
  event_type_id bigint      not null references public.event_types(id),   -- [PROBADO] FK
  "time"        timestamptz not null,                                     -- [PROBADO] timestamptz
  track_id      bigint,                                                   -- [INFERIDO] se deja NULLABLE: 0 nulls observados no prueba NOT NULL, y endurecerlo rompería la ingesta del N100 si produccion admite NULL
  zone          text,                                                     -- NULLABLE por evidencia del propio repo: dashboard_filter_options filtra `WHERE e.zone IS NOT NULL`
  gender        text,                                                     -- [PROBADO] NULLABLE (100% NULL en produccion)
  age           text,                                                     -- [PROBADO] NULLABLE (100% NULL en produccion)
  dwell_sec     numeric,                                                  -- [PROBADO] numeric + NULLABLE
  time_enter    timestamptz,                                              -- [PROBADO] timestamptz + NULLABLE
  time_end      timestamptz,                                              -- [PROBADO] timestamptz + NULLABLE
  clip_url      text                                                      -- [PROBADO] NULLABLE
);

-- Índice mínimo de consulta. Los índices de rendimiento reales los añaden
-- 20260829 (idx_events_local_day) y 20260831 (idx_events_camera_time_desc).
create index if not exists events_time_idx on public.events ("time" desc);

-- ─── tracking_logs_view ────────────────────────────────────────────────────
-- Vista que consume todo el dashboard. Ninguna migración la creaba; solo la
-- referenciaban. Reconstruida por introspección:
--   [PROBADO] 18 columnas, nombres, orden y tipos exactos.
--   [PROBADO] las columnas *_lima son `timestamp` sin zona y equivalen a
--             (col AT TIME ZONE 'America/Lima'): verificado comparando una fila
--             real, delta exacto de -5 h.
--   [PROBADO] count(vista) == count(events) -> no hay WHERE que descarte filas
--             ni join que las multiplique. De ahí los LEFT JOIN.
create or replace view public.tracking_logs_view as
select
  e.id                                          as event_id,
  s.name                                        as site,
  s.slug                                        as site_slug,
  c.channel                                     as channel,
  c.name                                        as camera_name,
  et.code                                       as event,
  e.zone                                        as zone,
  e."time"                                      as "time",
  e."time"      at time zone 'America/Lima'     as time_lima,
  e.track_id                                    as track_id,
  e.gender                                      as gender,
  e.age                                         as age,
  e.dwell_sec                                   as dwell_sec,
  e.time_enter                                  as time_enter,
  e.time_enter  at time zone 'America/Lima'     as time_enter_lima,
  e.time_end                                    as time_end,
  e.time_end    at time zone 'America/Lima'     as time_end_lima,
  e.clip_url                                    as clip_url
from public.events e
left join public.sites       s  on s.id  = e.site_id
left join public.cameras     c  on c.id  = e.camera_id
left join public.event_types et on et.id = e.event_type_id;

-- ─── keepalive ─────────────────────────────────────────────────────────────
-- Existe en produccion y NINGUNA migracion la creaba. La usa
-- prune_operational_data (20260903123000_unified_operational_retention.sql),
-- que aborta con 'relation "public.keepalive" does not exist' si falta.
-- [PROBADO] por introspeccion GraphQL: id BigInt! y ping_at Datetime!, ambos
-- NOT NULL. Hoy tiene 0 filas visibles para anon.
create table if not exists public.keepalive (
  id      bigint      generated by default as identity primary key,  -- [INFERIDO] identity
  ping_at timestamptz not null default now()                         -- [PROBADO] NOT NULL · [INFERIDO] default
);

-- ─── RLS: cerrado por defecto ──────────────────────────────────────────────
alter table public.events         enable row level security;
alter table public.sites          enable row level security;
alter table public.cameras        enable row level security;
alter table public.event_types    enable row level security;
alter table public.event_groups   enable row level security;
alter table public.person_classes enable row level security;
alter table public.keepalive      enable row level security;

notify pgrst, 'reload schema';
